version: "2"
services:
  notebook:
    user: "ubuntu"
    build: .
    ports:
      - 8888:8888
    volumes:
      - ~/Documents:/home/ubuntu/work
      - logs:/home/ubuntu/logs
    command: ["/run_jupyter.sh", "--ip=*", "--NotebookApp.token=''"]
  tensorboard:
    user: "ubuntu"
    build: .
    ports:
      - 6006:6006
    volumes_from:
      - notebook
    command: tensorboard --logdir /home/ubuntu/logs
volumes:
  logs:
